spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

